onboarding = false

[keys]
focus_pane_left = "ctrl+left"
focus_pane_down = "ctrl+down"
focus_pane_up = "ctrl+up"
focus_pane_right = "ctrl+right"

[theme]
name = "gruvbox"

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = false
